const countryList = {
  AED: "AE",
  AFN: "AF",
  XCD: "AG",
  ALL: "AL",
  AMD: "AM",
  ANG: "AN",
  AOA: "AO",
  AQD: "AQ",
  ARS: "AR",
  AUD: "AU",
  AZN: "AZ",
  BAM: "BA",
  BBD: "BB",
  BDT: "BD",
  XOF: "BE",
  BGN: "BG",
  BHD: "BH",
  BIF: "BI",
  BMD: "BM",
  BND: "BN",
  BOB: "BO",
  BRL: "BR",
  BSD: "BS",
  NOK: "BV",
  BWP: "BW",
  BYR: "BY",
  BZD: "BZ",
  CAD: "CA",
  CDF: "CD",
  XAF: "CF",
  CHF: "CH",
  CLP: "CL",
  CNY: "CN",
  COP: "CO",
  CRC: "CR",
  CUP: "CU",
  CVE: "CV",
  CYP: "CY",
  CZK: "CZ",
  DJF: "DJ",
  DKK: "DK",
  DOP: "DO",
  DZD: "DZ",
  ECS: "EC",
  EEK: "EE",
  EGP: "EG",
  ETB: "ET",
  EUR: "FR",
  FJD: "FJ",
  FKP: "FK",
  GBP: "GB",
  GEL: "GE",
  GGP: "GG",
  GHS: "GH",
  GIP: "GI",
  GMD: "GM",
  GNF: "GN",
  GTQ: "GT",
  GYD: "GY",
  HKD: "HK",
  HNL: "HN",
  HRK: "HR",
  HTG: "HT",
  HUF: "HU",
  IDR: "ID",
  ILS: "IL",
  INR: "IN",
  IQD: "IQ",
  IRR: "IR",
  ISK: "IS",
  JMD: "JM",
  JOD: "JO",
  JPY: "JP",
  KES: "KE",
  KGS: "KG",
  KHR: "KH",
  KMF: "KM",
  KPW: "KP",
  KRW: "KR",
  KWD: "KW",
  KYD: "KY",
  KZT: "KZ",
  LAK: "LA",
  LBP: "LB",
  LKR: "LK",
  LRD: "LR",
  LSL: "LS",
  LTL: "LT",
  LVL: "LV",
  LYD: "LY",
  MAD: "MA",
  MDL: "MD",
  MGA: "MG",
  MKD: "MK",
  MMK: "MM",
  MNT: "MN",
  MOP: "MO",
  MRO: "MR",
  MTL: "MT",
  MUR: "MU",
  MVR: "MV",
  MWK: "MW",
  MXN: "MX",
  MYR: "MY",
  MZN: "MZ",
  NAD: "NA",
  XPF: "NC",
  NGN: "NG",
  NIO: "NI",
  NPR: "NP",
  NZD: "NZ",
  OMR: "OM",
  PAB: "PA",
  PEN: "PE",
  PGK: "PG",
  PHP: "PH",
  PKR: "PK",
  PLN: "PL",
  PYG: "PY",
  QAR: "QA",
  RON: "RO",
  RSD: "RS",
  RUB: "RU",
  RWF: "RW",
  SAR: "SA",
  SBD: "SB",
  SCR: "SC",
  SDG: "SD",
  SEK: "SE",
  SGD: "SG",
  SKK: "SK",
  SLL: "SL",
  SOS: "SO",
  SRD: "SR",
  STD: "ST",
  SVC: "SV",
  SYP: "SY",
  SZL: "SZ",
  THB: "TH",
  TJS: "TJ",
  TMT: "TM",
  TND: "TN",
  TOP: "TO",
  TRY: "TR",
  TTD: "TT",
  TWD: "TW",
  TZS: "TZ",
  UAH: "UA",
  UGX: "UG",
  USD: "US",
  UYU: "UY",
  UZS: "UZ",
  VEF: "VE",
  VND: "VN",
  VUV: "VU",
  YER: "YE",
  ZAR: "ZA",
  ZMK: "ZM",
  ZWD: "ZW"
};



// const countryList = {
//   AED: "United Arab Emirates (AED)",
//   AFN: "Afghanistan (AFN)",
//   XCD: "Antigua and Barbuda (XCD)",
//   ALL: "Albania (ALL)",
//   AMD: "Armenia (AMD)",
//   ANG: "Netherlands Antilles (ANG)",
//   AOA: "Angola (AOA)",
//   AQD: "Antarctica (AQD)",
//   ARS: "Argentina (ARS)",
//   AUD: "Australia (AUD)",
//   AZN: "Azerbaijan (AZN)",
//   BAM: "Bosnia and Herzegovina (BAM)",
//   BBD: "Barbados (BBD)",
//   BDT: "Bangladesh (BDT)",
//   XOF: "West African CFA franc (XOF)",
//   BGN: "Bulgaria (BGN)",
//   BHD: "Bahrain (BHD)",
//   BIF: "Burundi (BIF)",
//   BMD: "Bermuda (BMD)",
//   BND: "Brunei (BND)",
//   BOB: "Bolivia (BOB)",
//   BRL: "Brazil (BRL)",
//   BSD: "Bahamas (BSD)",
//   NOK: "Norway (NOK)",
//   BWP: "Botswana (BWP)",
//   BYR: "Belarus (BYR)",
//   BZD: "Belize (BZD)",
//   CAD: "Canada (CAD)",
//   CDF: "Democratic Republic of the Congo (CDF)",
//   XAF: "Central African CFA franc (XAF)",
//   CHF: "Switzerland (CHF)",
//   CLP: "Chile (CLP)",
//   CNY: "China (CNY)",
//   COP: "Colombia (COP)",
//   CRC: "Costa Rica (CRC)",
//   CUP: "Cuba (CUP)",
//   CVE: "Cape Verde (CVE)",
//   CYP: "Cyprus (CYP)",
//   CZK: "Czech Republic (CZK)",
//   DJF: "Djibouti (DJF)",
//   DKK: "Denmark (DKK)",
//   DOP: "Dominican Republic (DOP)",
//   DZD: "Algeria (DZD)",
//   ECS: "Ecuador (ECS)",
//   EEK: "Estonia (EEK)",
//   EGP: "Egypt (EGP)",
//   ETB: "Ethiopia (ETB)",
//   EUR: "Eurozone (EUR)",
//   FJD: "Fiji (FJD)",
//   FKP: "Falkland Islands (FKP)",
//   GBP: "United Kingdom (GBP)",
//   GEL: "Georgia (GEL)",
//   GGP: "Guernsey (GGP)",
//   GHS: "Ghana (GHS)",
//   GIP: "Gibraltar (GIP)",
//   GMD: "Gambia (GMD)",
//   GNF: "Guinea (GNF)",
//   GTQ: "Guatemala (GTQ)",
//   GYD: "Guyana (GYD)",
//   HKD: "Hong Kong (HKD)",
//   HNL: "Honduras (HNL)",
//   HRK: "Croatia (HRK)",
//   HTG: "Haiti (HTG)",
//   HUF: "Hungary (HUF)",
//   IDR: "Indonesia (IDR)",
//   ILS: "Israel (ILS)",
//   INR: "India (INR)",
//   IQD: "Iraq (IQD)",
//   IRR: "Iran (IRR)",
//   ISK: "Iceland (ISK)",
//   JMD: "Jamaica (JMD)",
//   JOD: "Jordan (JOD)",
//   JPY: "Japan (JPY)",
//   KES: "Kenya (KES)",
//   KGS: "Kyrgyzstan (KGS)",
//   KHR: "Cambodia (KHR)",
//   KMF: "Comoros (KMF)",
//   KPW: "North Korea (KPW)",
//   KRW: "South Korea (KRW)",
//   KWD: "Kuwait (KWD)",
//   KYD: "Cayman Islands (KYD)",
//   KZT: "Kazakhstan (KZT)",
//   LAK: "Laos (LAK)",
//   LBP: "Lebanon (LBP)",
//   LKR: "Sri Lanka (LKR)",
//   LRD: "Liberia (LRD)",
//   LSL: "Lesotho (LSL)",
//   LTL: "Lithuania (LTL)",
//   LVL: "Latvia (LVL)",
//   LYD: "Libya (LYD)",
//   MAD: "Morocco (MAD)",
//   MDL: "Moldova (MDL)",
//   MGA: "Madagascar (MGA)",
//   MKD: "North Macedonia (MKD)",
//   MMK: "Myanmar (MMK)",
//   MNT: "Mongolia (MNT)",
//   MOP: "Macau (MOP)",
//   MRO: "Mauritania (MRO)",
//   MTL: "Malta (MTL)",
//   MUR: "Mauritius (MUR)",
//   MVR: "Maldives (MVR)",
//   MWK: "Malawi (MWK)",
//   MXN: "Mexico (MXN)",
//   MYR: "Malaysia (MYR)",
//   MZN: "Mozambique (MZN)",
//   NAD: "Namibia (NAD)",
//   XPF: "French Polynesia (XPF)",
//   NGN: "Nigeria (NGN)",
//   NIO: "Nicaragua (NIO)",
//   NPR: "Nepal (NPR)",
//   NZD: "New Zealand (NZD)",
//   OMR: "Oman (OMR)",
//   PAB: "Panama (PAB)",
//   PEN: "Peru (PEN)",
//   PGK: "Papua New Guinea (PGK)",
//   PHP: "Philippines (PHP)",
//   PKR: "Pakistan (PKR)",
//   PLN: "Poland (PLN)",
//   PYG: "Paraguay (PYG)",
//   QAR: "Qatar (QAR)",
//   RON: "Romania (RON)",
//   RSD: "Serbia (RSD)",
//   RUB: "Russia (RUB)",
//   RWF: "Rwanda (RWF)",
//   SAR: "Saudi Arabia (SAR)",
//   SBD: "Solomon Islands (SBD)",
//   SCR: "Seychelles (SCR)",
//   SDG: "Sudan (SDG)",
//   SEK: "Sweden (SEK)",
//   SGD: "Singapore (SGD)",
//   SKK: "Slovakia (SKK)",
//   SLL: "Sierra Leone (SLL)",
//   SOS: "Somalia (SOS)",
//   SRD: "Suriname (SRD)",
//   STD: "São Tomé and Príncipe (STD)",
//   SVC: "El Salvador (SVC)",
//   SYP: "Syria (SYP)",
//   SZL: "Eswatini (SZL)",
//   THB: "Thailand (THB)",
//   TJS: "Tajikistan (TJS)",
//   TMT: "Turkmenistan (TMT)",
//   TND: "Tunisia (TND)",
//   TOP: "Tonga (TOP)",
//   TRY: "Turkey (TRY)",
//   TTD: "Trinidad and Tobago (TTD)",
//   TWD: "Taiwan (TWD)",
//   TZS: "Tanzania (TZS)",
//   UAH: "Ukraine (UAH)",
//   UGX: "Uganda (UGX)",
//   USD: "United States (USD)",
//   UYU: "Uruguay (UYU)",
//   UZS: "Uzbekistan (UZS)",
//   VEF: "Venezuela (VEF)",
//   VND: "Vietnam (VND)",
//   VUV: "Vanuatu (VUV)",
//   YER: "Yemen (YER)",
//   ZAR: "South Africa (ZAR)",
//   ZMK: "Zambia (ZMK)",
//   ZWD: "Zimbabwe (ZWD)"
// };
